# Title: Even Fibonacci numbers
#
# Description:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def f(n)
  return n if n.zero? || n == 1
  f(n - 1) + f(n - 2)
end

i = 0
sum = 0

while (term = f(i)) < 4_000_000
  sum += term if term % 2 == 0
  i += 1
end

puts "The sum of the even-valued terms in the Fibonacci sequence whose values do not exceed four million is #{sum}"
